language: node_js
node_js: stable

# S: Build Lifecycle



script:
  - hexo g

# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/lifengsofts/lifengsofts.github.io.git